language: generic
sudo: false # use container based build

env:
    global:
        secure: "cHNnQq27CiFSOkDNpQaNbICh+Vo/gi8LUNW27UGIzCP/u/Ls6PFN6Hv2JQ1HLY/Yw15X8XaP4CotulfnfFoCkE6hPAMvmppMbh/rhd1mBoNNEmW1SEPHzKLE/OO+b5RkWYuurwGpfSYeo+QzQ0liGSBEK1U+tDU0/En6Rg0wZk/6LDf1e42Rpkpo1ZdrN4R3YA/uJlPC7Ld8R3K7oNosq1+g9JU9hpp4d2LBsaUzPopO3vNnMtWGbeNkk7npG0NNwepaT8uPpDer8AI8Li87y6aCgnx7fsofuPpEIZJ3Bp1ouu9k40yiVXKmwkCTpUXQvRka5tBVvn86vzz5v4rMbMV5dKl7S/8XUHbYaApHvVaK41PMyfPwvH17MdtZprYaZM0J+tVRVgH7KAPtaWpnIShglAJEqC77GA2VeiFggfklcEBvuWtPNq74zVe5CZ1/JN3v5jTga93+NSLjI5nIosXezelYzP5NyRWJE+y2MqHbm9iqriPajHs1zE9gomEOx5esmP3lZfNlFWuyEWylKroXOTyZbzcmycSbY2WLRRuMZywQOxd2SacMULMmxAMr9oM/GbOla2G/L+XHjskVSCxAkfi18XAFvXH21D/QE4E+zZZbJuZDwCtnVZci4k4dOo86pAdalntZ1tY7cDDIwv0VcA9c5XelFXMPKd4oboU="

matrix:
    include:
    # linux environments
    - env:
        - PYTHON_VERSION=3.7
      os: linux
    - env:
        - PYTHON_VERSION=3.6
      os: linux
      # osx environments
    - env:
        - PYTHON_VERSION=3.7
      os: osx
    - env:
        - PYTHON_VERSION=3.6
      os: osx

before_install:
    # define functions to unset and reset encrypted variables
    - function unset_secure {
          CONDA_TOKEN_SAVE=$CONDA_REPO_TOKEN;
          unset CONDA_REPO_TOKEN;
          }
    - function reset_secure {
          export CONDA_REPO_TOKEN=$CONDA_TOKEN_SAVE;
          }
    - unset_secure
    # increase open files limit
    - ulimit -a
    - ulimit -Sn 10000
    - ulimit -a
      # select the os name for the conda installer
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          OS_NAME=MacOSX;
      else
          OS_NAME=Linux;
      fi
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-"${OS_NAME}"-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export ORIGPATH=$PATH
    - export PATH="$HOME/miniconda/bin:$ORIGPATH"
    - hash -r
    - reset_secure

before_script:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
          export "DISPLAY=:99.0";
          sh -e /etc/init.d/xvfb start;
          sleep 3;
      fi

install:
    # unset the global CONDA_REPO_TOKEN variable because it is not needed
    # during the tests. This decreases the vulnerability
    - unset_secure
    - |
        echo ""
        echo "Configuring conda."
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda config --add channels chilipp/label/dev
        conda config --add channels chilipp/label/master
        conda config --add channels chilipp
        conda update -q conda
        conda install conda-build anaconda-client
        conda info -a
    - reset_secure
script:
    - unset_secure
    # install conda
    - PYTHONWARNINGS='ignore:mode:DeprecationWarning:docutils.io:245'
      conda build conda-recipe --python $PYTHON_VERSION
    # export the pw to make it available for the deploy
    - reset_secure

deploy:
  - provider: script
    script: ci/deploy_anaconda.py
    skip_cleanup: true
    on:
      all_branches: true
      repo: Chilipp/iucm
  - provider: script
    script: ci/deploy_anaconda.py
    skip_cleanup: true
    on:
      tags: true
      repo: Chilipp/iucm
