name: iucm_docs
channels:
    - chilipp/label/dev
    - chilipp/label/master
    - chilipp
dependencies:
    - python=3.7
    - xarray
    - netCDF4
    - matplotlib
    - seaborn
    - sphinx
    - cython
    - psy-simple
    - ipython
    - pyshp
    - scipy
    - pip:
        - sphinx-argparse
        - autodocsumm
