name: iucm_docs
channels:
    - chilipp/label/dev
    - conda-forge
dependencies:
    - python=3.6
    - xarray
    - netCDF4
    - matplotlib
    - seaborn
    - sphinx
    - cython
    - sphinx-argparse
    - autodocsumm
    - psyplot
    - psy-simple
    - ipython
    - pyshp
